import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import * as SecureStore from "expo-secure-store";

const STORAGE_KEY = "locale";
type Locale = "en" | "am" | "om";

const MESSAGES: Record<Locale, Record<string, string>> = {
  en: {
    "nav.products": "Products",
    "nav.cart": "Cart",
    "nav.account": "Account",
    "language.label": "Language",
    "language.english": "English",
    "language.amharic": "Amharic",
    "language.oromo": "Afan Oromo",
    "common.back": "Back",
    "common.loading": "Loading...",
    "common.view": "View",
    "common.soldOut": "Sold out",
    "common.inCart": "In cart",
    "common.items": "items",
    "common.stock": "Stock",
    "common.remove": "Remove",
    "common.subtotal": "Subtotal",
    "common.clear": "Clear",
    "common.continueShopping": "Continue shopping",
    "common.browseProducts": "Browse products",
    "common.current": "Current",
    "common.retry": "Retry",
    "common.saved": "Saved",
    "common.ok": "OK",
    "common.backToProducts": "Back to products",
    "common.signIn": "Sign in",
    "common.createAccount": "Create account",
    "common.tryAgain": "Try again",
    "common.loadingImage": "Loading image...",
    "common.availableNow": "Available now",
    "common.limitedStock": "Limited stock",
    "common.outOfStock": "Out of stock",
    "browse.market": "Market",
    "browse.title": "Fresh products ready to browse",
    "browse.subtitleSignedIn": "Browse fresh products, compare prices, and keep moving toward checkout.",
    "browse.subtitleSignedOut": "Explore products first. Sign in when you want to save a cart or place an order.",
    "browse.searchPlaceholder": "Search products",
    "browse.search": "Search",
    "browse.visibleProducts": "Visible products",
    "browse.sessionStatus": "Session status",
    "browse.featuredProducts": "Featured products",
    "browse.sectionCaption": "Tap a card to open details and add to cart.",
    "browse.loading": "Loading products...",
    "browse.couldNotLoad": "Could not load products",
    "browse.noProductsFound": "No products found",
    "browse.noProductsHint": "Try a different search term or refresh the list.",
    "browse.freshProduct": "Fresh product from a local farmer.",
    "browse.inCartMessage": "is now in your cart.",
    "browse.loadFailed": "Unable to load products.",
    "browse.stock.out": "Out of stock",
    "browse.stock.limited": "Limited stock",
    "browse.stock.available": "Available now",
    "checkout.title": "Checkout",
    "checkout.cartEmptyTitle": "Your cart is empty",
    "checkout.cartEmptyMessage": "Add products to continue with checkout.",
    "checkout.deliveryDetails": "Delivery details",
    "checkout.fullName": "Full name",
    "checkout.phoneNumber": "Phone number",
    "checkout.address": "Address",
    "checkout.city": "City",
    "checkout.deliveryNote": "Optional delivery note",
    "checkout.paymentMethod": "Payment method",
    "checkout.cashOnDelivery": "Cash on delivery",
    "checkout.chapa": "Chapa",
    "checkout.orderSummary": "Order summary",
    "checkout.itemsLabel": "Items",
    "checkout.deliveryFee": "Delivery fee",
    "checkout.serviceFee": "Service fee",
    "checkout.totalLabel": "Total",
    "checkout.placeOrder": "Place order",
    "checkout.openingChapa": "Opening Chapa...",
    "checkout.backToCart": "Back to cart",
    "checkout.missingDetailsTitle": "Missing details",
    "checkout.missingDetailsMessage": "Please fill in your name, phone, address, and city.",
    "checkout.orderPlacedTitle": "Order placed",
    "checkout.orderPlacedMessagePrefix": "Thanks",
    "checkout.paymentLabel": "Payment",
    "checkout.signInBeforeCheckout": "Please sign in before checkout.",
    "checkout.paymentCancelledTitle": "Payment cancelled",
    "checkout.paymentCancelledMessage": "You cancelled Chapa checkout.",
    "checkout.missingTxRef": "Missing transaction reference from Chapa.",
    "checkout.paymentFailedTitle": "Payment failed",
    "checkout.paymentFailedMessage": "Unable to complete Chapa payment.",
    "payment.verifying": "Verifying payment...",
    "payment.missingReference": "Missing payment reference.",
    "payment.signInRequired": "Please sign in and try again.",
    "payment.successMessage": "Payment successful. Your order is confirmed.",
    "payment.successTitle": "Payment successful",
    "payment.successToast": "Your order has been paid and confirmed.",
    "payment.verifyFailed": "Unable to verify payment.",
    "payment.verifyFailedTitle": "Payment verification failed",
    "payment.processing": "Processing Payment",
    "payment.complete": "Payment Complete",
    "payment.failed": "Payment Failed",
    "product.missingId": "Missing product id.",
    "product.loadFailed": "Unable to load this product.",
    "product.noDescription": "No description was provided for this product yet.",
    "product.unavailable": "This product is currently unavailable.",
    "product.addedToCart": "Added to cart",
    "product.addedToCartMessage": "was added to your cart.",
    "product.shareFailedTitle": "Share failed",
    "product.shareFailedMessage": "Unable to share this product right now.",
    "product.loading": "Loading product details...",
    "product.couldNotLoad": "Could not load product",
    "product.goBack": "Go back",
    "product.stock.out": "Out of stock",
    "product.stock.limited": "Limited stock",
    "product.stock.available": "Available now",
    "product.inStock": "in stock",
    "product.about": "About this product",
    "product.details": "Product details",
    "product.origin": "Origin",
    "product.flavorNotes": "Flavor notes",
    "product.roastLevel": "Roast level",
    "product.processingMethod": "Processing method",
    "product.processed": "Processed",
    "product.grindType": "Grind type",
    "product.grindSizes": "Grind sizes",
    "product.sustainable": "Sustainable",
    "product.farmer": "Farmer",
    "product.name": "Name",
    "product.email": "Email",
    "product.farmerId": "Farmer ID",
    "product.addToCart": "Add to cart",
    "product.buyNow": "Buy now",
    "product.viewCart": "View cart",
    "product.shareProduct": "Share product",
    "farmer.title": "Farmer Workspace",
    "farmer.subtitle": "Products, orders, earnings, visibility, and customer feedback.",
    "farmer.loading": "Loading farmer data...",
    "farmer.products": "Products",
    "farmer.pendingOrders": "Pending Orders",
    "farmer.earnings": "Earnings",
    "farmer.rating": "Rating",
    "farmer.inventoryAlerts": "Inventory Alerts",
    "farmer.noLowStock": "No low-stock products right now.",
    "farmer.recentOrders": "Recent Orders",
    "farmer.viewAll": "View all",
    "farmer.noIncomingOrders": "No incoming orders yet.",
    "farmer.latestProducts": "Latest Products",
    "farmer.manage": "Manage",
    "farmer.noProductsYet": "No products yet.",
    "farmer.editProduct": "Edit Product",
    "farmer.addProduct": "Add Product",
    "farmer.productName": "Product name",
    "farmer.price": "Price",
    "farmer.stock": "Stock",
    "farmer.description": "Description, category, unit type, seasonal notes",
    "farmer.cancel": "Cancel",
    "farmer.saveProduct": "Save Product",
    "farmer.createProduct": "Create Product",
    "farmer.productManagement": "Product Management",
    "farmer.incomingOrders": "Incoming Orders",
    "farmer.paymentSummary": "Payment Summary",
    "farmer.chapaTransactions": "Chapa Transactions",
    "farmer.noPaymentTransactions": "No payment transactions yet.",
    "farmer.farmerProfile": "Farmer Profile",
    "farmer.farmName": "Farm name",
    "farmer.ownerEmail": "Owner email",
    "farmer.phone": "Phone",
    "farmer.addInProfileSettings": "Add in profile settings",
    "farmer.location": "Location",
    "farmer.noLocationYet": "No location yet",
    "farmer.status": "Status",
    "farmer.coordinates": "Coordinates",
    "farmer.notSet": "Not set",
    "farmer.editProfile": "Edit Profile",
    "farmer.settings": "Settings",
    "farmer.language": "Language",
    "farmer.appearance": "Appearance",
    "farmer.logout": "Logout",
    "farmer.reviewsAndRatings": "Reviews and Ratings",
    "farmer.noReviewsYet": "No reviews yet.",
    "farmer.chooseProductImage": "Choose product image",
    "farmer.replaceImage": "Replace image",
    "farmer.browseStorage": "Browse storage",
    "farmer.loadingImage": "Loading image...",
    "farmer.loadingData": "Loading...",
    "farmer.accept": "Accept",
    "farmer.reject": "Reject",
    "farmer.packed": "Packed",
    "farmer.delivered": "Delivered",
    "farmer.out": "Out",
    "farmer.left": "left",
    "farmer.buyer": "Buyer",
    "farmer.qty": "Qty",
    "farmer.total": "Total",
    "farmer.delivery": "Delivery",
    "farmer.payment": "Payment",
    "farmer.today": "Today",
    "farmer.thisWeek": "This Week",
    "farmer.thisMonth": "This Month",
    "farmer.paid": "Paid",
    "farmer.paidPayments": "Paid payments",
    "farmer.pendingPayments": "Pending payments",
    "farmer.totalEarnings": "Total earnings",
    "auth.signInTitle": "Sign in",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.continue": "Continue",
    "auth.continueWithGoogle": "Continue with Google",
    "auth.createAccount": "Create an account",
    "auth.selectRole": "Select role",
    "auth.buyerRole": "Buyer",
    "auth.farmerRole": "Farmer",
    "auth.additionalSteps": "Sign-in requires additional steps that are not implemented on this screen.",
    "auth.signInFailed": "Unable to sign in.",
    "auth.googleFailed": "Unable to sign in with Google.",
    "account.title": "Account",
    "account.subtitle": "Manage your orders, profile, language, and app settings.",
    "account.guest": "You are not signed in",
    "account.signIn": "Sign in",
    "account.editProfile": "Edit Profile",
    "account.orders": "Orders",
    "account.profile": "Profile",
    "account.language": "Language",
    "account.settings": "Settings",
    "account.appearance": "Appearance",
    "account.darkMode": "Dark mode",
    "account.lightMode": "Light mode",
    "account.signedInAs": "Signed in as",
    "account.signOut": "Sign out",
    "orders.title": "Orders",
    "orders.empty": "No orders yet. Your order history will appear here.",
    "orders.signInPrompt": "Sign in to view your orders.",
    "orders.loading": "Loading orders...",
    "orders.items": "Items",
    "orders.city": "City",
    "profile.title": "Profile",
    "profile.empty": "Profile details screen is ready for your user data.",
    "profile.signInPrompt": "Sign in to view your profile.",
    "profile.loading": "Loading profile...",
    "profile.firstName": "First name",
    "profile.lastName": "Last name",
    "profile.address": "Address",
    "profile.email": "Email",
    "profile.saveChanges": "Save changes",
    "cart.back": "Back",
    "cart.title": "My cart",
    "cart.emptyTitle": "Your cart is empty",
    "cart.emptyText": "Browse products and tap Add to cart.",
    "cart.browseProducts": "Browse products",
    "cart.stock": "Stock",
    "cart.remove": "Remove",
    "cart.subtotal": "Subtotal",
    "cart.checkout": "Proceed to checkout",
    "cart.continueShopping": "Continue shopping",
    "cart.clearCart": "Clear cart",
    "cart.item.one": "item",
    "cart.item.other": "items",
    "buyer.title": "Buyer Marketplace",
    "buyer.subtitle": "Farmer uploads appear here for you to browse and purchase from.",
    "buyer.productsCount": "Products",
    "buyer.loading": "Loading products...",
    "buyer.empty": "No products yet. Farmer uploads will appear here.",
    "buyer.error": "Unable to load products.",
    "buyer.addToCart": "Add to cart",
    "buyer.view": "View",
    "buyer.soldOut": "Sold out",
  },
  am: {
    "nav.products": "ምርቶች",
    "nav.cart": "ጋሪ",
    "nav.account": "መለያ",
    "language.label": "ቋንቋ",
    "language.english": "እንግሊዝኛ",
    "language.amharic": "አማርኛ",
    "language.oromo": "አፋን ኦሮሞ",
    "common.back": "ተመለስ",
    "common.loading": "በመጫን ላይ...",
    "common.view": "እይታ",
    "common.soldOut": "አልቋል",
    "common.inCart": "በጋሪ",
    "common.items": "እቃዎች",
    "common.stock": "ክምችት",
    "common.remove": "አስወግድ",
    "common.subtotal": "ንዑስ ድምር",
    "common.clear": "አጽዳ",
    "common.continueShopping": "ግዢን ቀጥል",
    "common.browseProducts": "ምርቶችን ይመልከቱ",
    "common.current": "አሁን ያለው",
    "common.retry": "እንደገና ሞክር",
    "common.saved": "ተቀምጧል",
    "common.ok": "እሺ",
    "common.backToProducts": "ወደ ምርቶች ተመለስ",
    "common.signIn": "ግባ",
    "common.createAccount": "መለያ ፍጠር",
    "common.tryAgain": "እንደገና ሞክር",
    "common.loadingImage": "ምስል በመጫን ላይ...",
    "common.availableNow": "አሁን ይገኛል",
    "common.limitedStock": "የተወሰነ ክምችት",
    "common.outOfStock": "አልቋል",
    "browse.market": "ገበያ",
    "browse.title": "ትኩስ ምርቶች ዝግጁ ናቸው",
    "browse.subtitleSignedIn": "ትኩስ ምርቶችን ይመልከቱ፣ ዋጋዎችን ያነፃፅሩ፣ ወደ ክፍያ ይቀጥሉ።",
    "browse.subtitleSignedOut": "መጀመሪያ ምርቶችን ይመልከቱ። ጋሪ ለማስቀመጥ ወይም ትዕዛዝ ለማድረግ ይግቡ።",
    "browse.searchPlaceholder": "ምርቶችን ይፈልጉ",
    "browse.search": "ፈልግ",
    "browse.visibleProducts": "የሚታዩ ምርቶች",
    "browse.sessionStatus": "የክፍለ-ጊዜ ሁኔታ",
    "browse.featuredProducts": "የተመረጡ ምርቶች",
    "browse.sectionCaption": "ዝርዝሮችን ለማየት ካርዱን ይንኩ።",
    "browse.loading": "ምርቶች በመጫን ላይ...",
    "browse.couldNotLoad": "ምርቶችን መጫን አልተቻለም",
    "browse.noProductsFound": "ምንም ምርት አልተገኘም",
    "browse.noProductsHint": "ሌላ የፍለጋ ቃል ይሞክሩ ወይም ዝርዝሩን ያድሱ።",
    "browse.freshProduct": "ከአካባቢ ገበሬ የመጣ ትኩስ ምርት።",
    "browse.inCartMessage": "አሁን በጋሪዎ ውስጥ ነው።",
    "browse.loadFailed": "ምርቶችን መጫን አልተቻለም።",
    "browse.stock.out": "አልቋል",
    "browse.stock.limited": "የተወሰነ ክምችት",
    "browse.stock.available": "አሁን ይገኛል",
    "checkout.title": "ክፍያ",
    "checkout.cartEmptyTitle": "ጋሪዎ ባዶ ነው",
    "checkout.cartEmptyMessage": "ክፍያን ለመቀጠል ምርቶችን ያክሉ።",
    "checkout.deliveryDetails": "የማድረሻ ዝርዝሮች",
    "checkout.fullName": "ሙሉ ስም",
    "checkout.phoneNumber": "ስልክ ቁጥር",
    "checkout.address": "አድራሻ",
    "checkout.city": "ከተማ",
    "checkout.deliveryNote": "አማራጭ የማድረሻ ማስታወሻ",
    "checkout.paymentMethod": "የክፍያ ዘዴ",
    "checkout.cashOnDelivery": "በተደርሶ ጊዜ ክፍያ",
    "checkout.chapa": "ቻፓ",
    "checkout.orderSummary": "የትዕዛዝ ማጠቃለያ",
    "checkout.itemsLabel": "እቃዎች",
    "checkout.deliveryFee": "የማድረሻ ክፍያ",
    "checkout.serviceFee": "የአገልግሎት ክፍያ",
    "checkout.totalLabel": "ጠቅላላ",
    "checkout.placeOrder": "ትዕዛዝ አስገባ",
    "checkout.openingChapa": "ቻፓ በመክፈት ላይ...",
    "checkout.backToCart": "ወደ ጋሪ ተመለስ",
    "checkout.missingDetailsTitle": "ዝርዝሮች ጎድለዋል",
    "checkout.missingDetailsMessage": "እባክዎ ስም፣ ስልክ፣ አድራሻ እና ከተማ ያስገቡ።",
    "checkout.orderPlacedTitle": "ትዕዛዝ ተመዝግቧል",
    "checkout.orderPlacedMessagePrefix": "እናመሰግናለን",
    "checkout.paymentLabel": "ክፍያ",
    "checkout.signInBeforeCheckout": "እባክዎ ክፍያ በፊት ይግቡ።",
    "checkout.paymentCancelledTitle": "ክፍያ ተሰርዟል",
    "checkout.paymentCancelledMessage": "የቻፓ ክፍያን ተሰርዘዋል።",
    "checkout.missingTxRef": "ከቻፓ የተላከ የግብይት መለያ ጎድሎታል።",
    "checkout.paymentFailedTitle": "ክፍያ አልተሳካም",
    "checkout.paymentFailedMessage": "የቻፓ ክፍያን ማጠናቀቅ አልተቻለም።",
    "payment.verifying": "ክፍያ በማረጋገጥ ላይ...",
    "payment.missingReference": "የክፍያ መለያ ጎድሏል።",
    "payment.signInRequired": "እባክዎ ይግቡና እንደገና ይሞክሩ።",
    "payment.successMessage": "ክፍያ ተሳክቷል። ትዕዛዝዎ ተረጋግጧል።",
    "payment.successTitle": "ክፍያ ተሳክቷል",
    "payment.successToast": "ትዕዛዝዎ ተከፍሏል እና ተረጋግጧል።",
    "payment.verifyFailed": "ክፍያን ማረጋገጥ አልተቻለም።",
    "payment.verifyFailedTitle": "ክፍያ ማረጋገጥ አልተሳካም",
    "payment.processing": "ክፍያ በማካሄድ ላይ",
    "payment.complete": "ክፍያ ተጠናቀቀ",
    "payment.failed": "ክፍያ አልተሳካም",
    "product.missingId": "የምርት መታወቂያ ጎድሏል።",
    "product.loadFailed": "ይህን ምርት መጫን አልተቻለም።",
    "product.noDescription": "ለዚህ ምርት እስካሁን መግለጫ አልተሰጠም።",
    "product.unavailable": "ይህ ምርት አሁን አይገኝም።",
    "product.addedToCart": "ወደ ጋሪ ተጨምሯል",
    "product.addedToCartMessage": "ወደ ጋሪዎ ተጨምሯል።",
    "product.shareFailedTitle": "ማጋራት አልተሳካም",
    "product.shareFailedMessage": "ይህን ምርት አሁን ማጋራት አልተቻለም።",
    "product.loading": "የምርት ዝርዝሮች በመጫን ላይ...",
    "product.couldNotLoad": "ምርት መጫን አልተቻለም",
    "product.goBack": "ተመለስ",
    "product.stock.out": "አልቋል",
    "product.stock.limited": "የተወሰነ ክምችት",
    "product.stock.available": "አሁን ይገኛል",
    "product.inStock": "በክምችት ውስጥ",
    "product.about": "ስለዚህ ምርት",
    "product.details": "የምርት ዝርዝሮች",
    "product.origin": "ምንጭ",
    "product.flavorNotes": "የጣዕም ማስታወሻዎች",
    "product.roastLevel": "የመቆጣጠሪያ ደረጃ",
    "product.processingMethod": "የማቀናበር ዘዴ",
    "product.processed": "ተቀናብሯል",
    "product.grindType": "የመፍጨት አይነት",
    "product.grindSizes": "የመፍጨት መጠኖች",
    "product.sustainable": "ዘላቂ",
    "product.farmer": "ገበሬ",
    "product.name": "ስም",
    "product.email": "ኢሜይል",
    "product.farmerId": "የገበሬ መታወቂያ",
    "product.addToCart": "ወደ ጋሪ ጨምር",
    "product.buyNow": "አሁን ግዛ",
    "product.viewCart": "ጋሪ እይ",
    "product.shareProduct": "ምርት አጋራ",
    "farmer.title": "የገበሬ መድረክ",
    "farmer.subtitle": "ምርቶች፣ ትዕዛዞች፣ ገቢ፣ ታይነት እና የደንበኛ አስተያየት።",
    "farmer.loading": "የገበሬ መረጃ በመጫን ላይ...",
    "farmer.products": "ምርቶች",
    "farmer.pendingOrders": "በመጠባበቅ ላይ ያሉ ትዕዛዞች",
    "farmer.earnings": "ገቢ",
    "farmer.rating": "ደረጃ",
    "farmer.inventoryAlerts": "የክምችት ማስጠንቀቂያዎች",
    "farmer.noLowStock": "አሁን ዝቅተኛ ክምችት ያላቸው ምርቶች የሉም።",
    "farmer.recentOrders": "የቅርብ ጊዜ ትዕዛዞች",
    "farmer.viewAll": "ሁሉንም ይመልከቱ",
    "farmer.noIncomingOrders": "ገና የገቡ ትዕዛዞች የሉም።",
    "farmer.latestProducts": "የቅርብ ጊዜ ምርቶች",
    "farmer.manage": "አስተዳድር",
    "farmer.noProductsYet": "እስካሁን ምርት የለም።",
    "farmer.editProduct": "ምርት አርም",
    "farmer.addProduct": "ምርት አክል",
    "farmer.productName": "የምርት ስም",
    "farmer.price": "ዋጋ",
    "farmer.stock": "ክምችት",
    "farmer.description": "መግለጫ፣ ምድብ፣ የክፍል አይነት፣ የወቅት ማስታወሻዎች",
    "farmer.cancel": "ሰርዝ",
    "farmer.saveProduct": "ምርት አስቀምጥ",
    "farmer.createProduct": "ምርት ፍጠር",
    "farmer.productManagement": "የምርት አስተዳደር",
    "farmer.incomingOrders": "የሚገቡ ትዕዛዞች",
    "farmer.paymentSummary": "የክፍያ ማጠቃለያ",
    "farmer.chapaTransactions": "የቻፓ ግብይቶች",
    "farmer.noPaymentTransactions": "እስካሁን የክፍያ ግብይቶች የሉም።",
    "farmer.farmerProfile": "የገበሬ ፕሮፋይል",
    "farmer.farmName": "የእርሻ ስም",
    "farmer.ownerEmail": "የባለቤት ኢሜይል",
    "farmer.phone": "ስልክ",
    "farmer.addInProfileSettings": "በፕሮፋይል ቅንብሮች ውስጥ አክል",
    "farmer.location": "አካባቢ",
    "farmer.noLocationYet": "እስካሁን አካባቢ የለም",
    "farmer.status": "ሁኔታ",
    "farmer.coordinates": "ኮርዲኔቶች",
    "farmer.notSet": "አልተዘጋጀም",
    "farmer.editProfile": "ፕሮፋይል አርም",
    "farmer.settings": "ቅንብሮች",
    "farmer.language": "ቋንቋ",
    "farmer.appearance": "መልክ",
    "farmer.logout": "ውጣ",
    "farmer.reviewsAndRatings": "ግምገማዎች እና ደረጃዎች",
    "farmer.noReviewsYet": "እስካሁን ግምገማ የለም።",
    "farmer.chooseProductImage": "የምርት ምስል ምረጥ",
    "farmer.replaceImage": "ምስል ቀይር",
    "farmer.browseStorage": "ማከማቻ ይመልከቱ",
    "farmer.loadingImage": "ምስል በመጫን ላይ...",
    "farmer.loadingData": "በመጫን ላይ...",
    "farmer.accept": "ተቀበል",
    "farmer.reject": "ውድቀት",
    "farmer.packed": "ተዘጋጅቷል",
    "farmer.delivered": "ደርሷል",
    "farmer.out": "ውጪ",
    "farmer.left": "ቀረ",
    "farmer.buyer": "ገዢ",
    "farmer.qty": "ብዛት",
    "farmer.total": "ጠቅላላ",
    "farmer.delivery": "ማድረሻ",
    "farmer.payment": "ክፍያ",
    "farmer.today": "ዛሬ",
    "farmer.thisWeek": "ይህ ሳምንት",
    "farmer.thisMonth": "ይህ ወር",
    "farmer.paid": "ተከፍሏል",
    "farmer.paidPayments": "የተከፈሉ ክፍያዎች",
    "farmer.pendingPayments": "የሚጠባበቁ ክፍያዎች",
    "farmer.totalEarnings": "ጠቅላላ ገቢ",
    "auth.signInTitle": "ግባ",
    "auth.email": "ኢሜይል",
    "auth.password": "የይለፍ ቃል",
    "auth.continue": "ቀጥል",
    "auth.continueWithGoogle": "በGoogle ቀጥል",
    "auth.createAccount": "መለያ ፍጠር",
    "auth.selectRole": "ሚና ምረጥ",
    "auth.buyerRole": "ገዢ",
    "auth.farmerRole": "ገበሬ",
    "auth.additionalSteps": "መግቢያው ተጨማሪ ደረጃዎችን ይፈልጋል፣ ነገር ግን በዚህ ገጽ አልተገነባም።",
    "auth.signInFailed": "መግባት አልተቻለም።",
    "auth.googleFailed": "በGoogle መግባት አልተቻለም።",
    "account.title": "መለያ",
    "account.subtitle": "ትዕዛዞችን፣ ፕሮፋይልን፣ ቋንቋን እና የመተግበሪያ ቅንብሮችን ያስተዳድሩ።",
    "account.guest": "አልገቡም",
    "account.signIn": "ግባ",
    "account.editProfile": "ፕሮፋይልን አስተካክል",
    "account.orders": "ትዕዛዞች",
    "account.profile": "ፕሮፋይል",
    "account.language": "ቋንቋ",
    "account.settings": "ቅንብሮች",
    "account.appearance": "መልክ",
    "account.darkMode": "ጨለማ ሁኔታ",
    "account.lightMode": "ብርሃን ሁኔታ",
    "account.signedInAs": "የገቡት",
    "account.signOut": "ውጣ",
    "orders.title": "ትዕዛዞች",
    "orders.empty": "እስካሁን ትዕዛዝ የለም። ታሪክዎ እዚህ ይታያል።",
    "orders.signInPrompt": "ትዕዛዞችዎን ለማየት ይግቡ።",
    "orders.loading": "ትዕዛዞች በመጫን ላይ...",
    "orders.items": "እቃዎች",
    "orders.city": "ከተማ",
    "profile.title": "ፕሮፋይል",
    "profile.empty": "የፕሮፋይል ዝርዝሮች ገጽ ለተጠቃሚ መረጃ ዝግጁ ነው።",
    "profile.signInPrompt": "ፕሮፋይልዎን ለማየት ይግቡ።",
    "profile.loading": "ፕሮፋይል በመጫን ላይ...",
    "profile.firstName": "የመጀመሪያ ስም",
    "profile.lastName": "የአባት ስም",
    "profile.address": "አድራሻ",
    "profile.email": "ኢሜይል",
    "profile.saveChanges": "ለውጦችን አስቀምጥ",
    "cart.back": "ተመለስ",
    "cart.title": "የእኔ ጋሪ",
    "cart.emptyTitle": "ጋሪዎ ባዶ ነው",
    "cart.emptyText": "ምርቶችን ይመልከቱ እና ወደ ጋሪ አክል ይጫኑ።",
    "cart.browseProducts": "ምርቶችን ይመልከቱ",
    "cart.stock": "እቃ",
    "cart.remove": "አስወግድ",
    "cart.subtotal": "ጠቅላላ",
    "cart.checkout": "ወደ ክፍያ ቀጥል",
    "cart.continueShopping": "ግዢን ቀጥል",
    "cart.clearCart": "ጋሪውን አጽዳ",
    "cart.item.one": "እቃ",
    "cart.item.other": "እቃዎች",
    "buyer.title": "የገዢ ገበያ",
    "buyer.subtitle": "የገበሬ ምርቶች እዚህ ይታያሉ። ይመልከቱ እና ይግዙ።",
    "buyer.productsCount": "ምርቶች",
    "buyer.loading": "ምርቶች በመጫን ላይ...",
    "buyer.empty": "እስካሁን ምርት የለም። የገበሬ ጭነቶች እዚህ ይታያሉ።",
    "buyer.error": "ምርቶችን መጫን አልተቻለም።",
    "buyer.addToCart": "ወደ ጋሪ ጨምር",
    "buyer.view": "ይመልከቱ",
    "buyer.soldOut": "አልቋል",
  },
  om: {
    "nav.products": "Oomishaalee",
    "nav.cart": "Gaarii",
    "nav.account": "Akoontii",
    "language.label": "Afaan",
    "language.english": "Ingiliffa",
    "language.amharic": "Afaan Amaaraa",
    "language.oromo": "Afaan Oromoo",
    "common.back": "Deebi'i",
    "common.loading": "Fe'amaa jira...",
    "common.view": "Ilaali",
    "common.soldOut": "Dhumeera",
    "common.inCart": "Gaaritti",
    "common.items": "wantoota",
    "common.stock": "Kuusaa",
    "common.remove": "Haqi",
    "common.subtotal": "Waliigala xiqqaa",
    "common.clear": "Qulqulleessi",
    "common.continueShopping": "Bittaa itti fufi",
    "common.browseProducts": "Oomishaalee ilaali",
    "common.current": "Amma",
    "common.retry": "Irra deebi'ii yaali",
    "common.saved": "Kuufameera",
    "common.ok": "Eeyyee",
    "common.backToProducts": "Gara oomishaalee deebi'i",
    "common.signIn": "Seeni",
    "common.createAccount": "Herrega uumi",
    "common.tryAgain": "Irra deebi'ii yaali",
    "common.loadingImage": "Suuraa fe'amaa jira...",
    "common.availableNow": "Amma ni argama",
    "common.limitedStock": "Kuusaa daangeffame",
    "common.outOfStock": "Dhumeera",
    "auth.signInTitle": "Seeni",
    "auth.email": "Imeelii",
    "auth.password": "Jecha icciitii",
    "auth.continue": "Itti fufi",
    "auth.continueWithGoogle": "Google'n itti fufi",
    "auth.createAccount": "Herrega haaraa uumi",
    "auth.selectRole": "Gahee filadhu",
    "auth.buyerRole": "Bitataa",
    "auth.farmerRole": "Qonnaan bulaa",
    "auth.additionalSteps": "Seenuuf tarkaanfii dabalataa barbaada; fuula kana irratti hin qophaa'in.",
    "auth.signInFailed": "Seenuu hin danda'amne.",
    "auth.googleFailed": "Google'n seenuu hin danda'amne.",
    "account.title": "Akoontii",
    "account.subtitle": "Ajaja, piroofaayilii, afaanii fi qindaa'ina appii to'achiisi.",
    "account.guest": "Hin seeniin",
    "account.signIn": "Seeni",
    "account.editProfile": "Piroofaayilii gulaali",
    "account.orders": "Ajajoota",
    "account.profile": "Piroofaayilii",
    "account.language": "Afaan",
    "account.settings": "Qindaa'ina",
    "account.appearance": "Bifa",
    "account.darkMode": "Haala dukkanaa",
    "account.lightMode": "Haala ifaa",
    "account.signedInAs": "Kan seene",
    "account.signOut": "Ba'i",
    "orders.title": "Ajajoota",
    "orders.empty": "Ammaaf ajajni hin jiru. Seenaa ajaja kee asitti mul'ata.",
    "orders.signInPrompt": "Ajajoota kee ilaaluuf seeni.",
    "orders.loading": "Ajajoota fe'amaa jiru...",
    "orders.items": "Oomishaalee",
    "orders.city": "Magaalaa",
    "profile.title": "Piroofaayilii",
    "profile.empty": "Fuulli ibsa piroofaayilii odeeffannoo fayyadamaa keetiif qophaa'eera.",
    "profile.signInPrompt": "Piroofaayilii kee ilaaluf seeni.",
    "profile.loading": "Piroofaayilii fe'amaa jira...",
    "profile.firstName": "Maqaa jalqabaa",
    "profile.lastName": "Maqaa abbaa",
    "profile.address": "Teessoo",
    "profile.email": "Imeelii",
    "profile.saveChanges": "Jijjiirama olkaa'i",
    "cart.back": "Duubatti",
    "cart.title": "Gaarii koo",
    "cart.emptyTitle": "Gaariin kee duwwaa dha",
    "cart.emptyText": "Oomishaalee ilaaliitii Add to cart tuqi.",
    "cart.browseProducts": "Oomishaalee ilaali",
    "cart.stock": "Kuusaa",
    "cart.remove": "Haqi",
    "cart.subtotal": "Waliigala xiqqaa",
    "cart.checkout": "Kaffaltiitti itti fufi",
    "cart.continueShopping": "Bittaa itti fufi",
    "cart.clearCart": "Gaarii qulqulleessi",
    "cart.item.one": "oomisha",
    "cart.item.other": "oomishaalee",
    "buyer.title": "Gabaa Bittootaa",
    "buyer.subtitle": "Oomishoonni qonnaan bultootaa asitti ni mul'atu; ilaalii bitadhaa.",
    "buyer.productsCount": "Oomishaalee",
    "buyer.loading": "Oomishaalee fe'amaa jiru...",
    "buyer.empty": "Ammaaf oomishni hin jiru. Fe'awwan qonnaan bultootaa asitti ni mul'atu.",
    "buyer.error": "Oomishaalee fe'uu hin danda'amne.",
    "buyer.addToCart": "Gara gaarii dabali",
    "buyer.view": "Ilaali",
    "buyer.soldOut": "Dhumeera",
  },
};

type TranslationKey = string;

type LanguageContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: TranslationKey) => string;
  getCountLabel: (count: number) => string;
  isReady: boolean;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    let mounted = true;

    const hydrateLocale = async () => {
      const savedLocale = await SecureStore.getItemAsync(STORAGE_KEY);

      if (!mounted) {
        return;
      }

      if (savedLocale === "en" || savedLocale === "am" || savedLocale === "om") {
        setLocaleState(savedLocale);
      }

      setIsReady(true);
    };

    void hydrateLocale();

    return () => {
      mounted = false;
    };
  }, []);

  useEffect(() => {
    if (!isReady) {
      return;
    }

    void SecureStore.setItemAsync(STORAGE_KEY, locale);
  }, [isReady, locale]);

  const setLocale = (nextLocale: Locale) => {
    setLocaleState(nextLocale);
  };

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: TranslationKey) => MESSAGES[locale][key] ?? MESSAGES.en[key] ?? key;
    const getCountLabel = (count: number) => `${count} ${count === 1 ? t("cart.item.one") : t("cart.item.other")}`;

    return {
      locale,
      setLocale,
      t,
      getCountLabel,
      isReady,
    };
  }, [isReady, locale]);

  return <LanguageContext.Provider value={value}>{isReady ? children : null}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}

export type { Locale, TranslationKey };
